### ISSUE TITLE
Update latest release to 0.4.4

### ISSUE THREAD

**Issue by simenbrekken** [mcasper/git-clean#22]
I'm attempting to install git-clean via a brew recipe that uses the release tarball. Any chance you could bump the latest release to 0.4.4?

**Comment by mcasper** [comment]
Hey @simenbrekken! 

I'm assuming that you installed from https://github.com/mikeastock/homebrew-git-clean, which I don't control. I have wanted to get this onto Homebrew for awhile, so I'll take this as an excuse to whip up a formula, stand by!

**Comment by mcasper** [comment]
Would you mind checking out the homebrew installation instructions in https://github.com/mcasper/git-clean/pull/23 and confirming that they work for you?

**Comment by simenbrekken** [comment]
@mcasper Works like a charm!

**Comment by mcasper** [comment]
Wonderful!
