### ISSUE TITLE
ignoring branches

### ISSUE THREAD

**Issue by phoet** [mcasper/git-clean#24]
it would be great to have an option to exclude specific branches. it would be even nicer to have a `.git-clean` file or something to persist the configuration for the next run.

use-case here:

following the git-flow workflow, we have master & production as permanent branches that must not be deleted.

i have no experience with rust. i might take a peak though and see if i can patch it myself if this addition is welcome.

**Comment by mcasper** [comment]
Hey @phoet, I fully support both of those ideas. I've been meaning to add an ignore option for awhile...

If you want to take a stab at learning Rust and implementing the feature that would be great, otherwise I can probably get to it this weekend
